switch to firefox for ng test
$ time ng test
Compiling @angular/core : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/material/core : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling @angular/material/button : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/material/snack-bar : es2015 as esm2015
⠋ Generating browser application bundles...23 01 2021 04:00:39.065:WARN [karma]: No captured browser, open http://localhost:9876/
23 01 2021 04:00:39.078:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
23 01 2021 04:00:39.078:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
⠙ Generating browser application bundles (phase: building)...23 01 2021 04:00:39.086:INFO [launcher]: Starting browser Chrome
23 01 2021 04:00:39.087:ERROR [launcher]: No binary for Chrome browser on your platform.
  Please, set "CHROME_BIN" env variable.
✔ Browser application bundle generation complete.
⠋ Generating browser application bundles...23 01 2021 04:00:48.533:WARN [karma]: No captured browser, open http://localhost:9876/
✔ Browser application bundle generation complete.
23 01 2021 04:01:04.345:INFO [Firefox 85.0 (Windows 10)]: Connected on socket 8_x4ncqDCrG4FfcOAAAA with id manual-9490
23 01 2021 04:01:16.145:WARN [Firefox 85.0 (Windows 10)]: Disconnected (0 times)Client disconnected from CONNECTED state (transport close)
Firefox 85.0 (Windows 10) ERROR
  DisconnectedClient disconnected from CONNECTED state (transport close)

Firefox 85.0 (Windows 10) ERROR
  DisconnectedClient disconnected from CONNECTED state (transport close)
^C
real    1m13.259s
user    1m23.068s
sys     0m3.293s
[kushal@april87 coloradoquiz]$ git add .; git commit; git push origin master;[master 7c922dd] wip
 1 file changed, 4 insertions(+)
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 4 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 1.18 KiB | 1.18 MiB/s, done.
Total 6 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:teamkushal/coloradoquiz.git
   8d9b6bb..7c922dd  master -> master
[kushal@april87 coloradoquiz]$ time yarn add karma-jasmine karma-jasmine karma-chrome-launcher karma-jasmine-html-reporter karma-coverage-istanbul-reporter karma-firefox-launcher karma-jasmine-html-reporter karma-spec-reporter
yarn add v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
warning "karma-jasmine" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
warning "karma-chrome-launcher" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
warning "karma-jasmine-html-reporter" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
success Saved 5 new dependencies.
info Direct dependencies
├─ karma-chrome-launcher@3.1.0
├─ karma-coverage-istanbul-reporter@3.0.3
├─ karma-firefox-launcher@2.1.0
└─ karma-spec-reporter@0.0.32
info All dependencies
├─ istanbul-lib-source-maps@3.0.6
├─ karma-chrome-launcher@3.1.0
├─ karma-coverage-istanbul-reporter@3.0.3
├─ karma-firefox-launcher@2.1.0
└─ karma-spec-reporter@0.0.32
Done in 8.62s.

real    0m8.824s
user    0m9.558s
sys     0m1.500s
[kushal@april87 coloradoquiz]$ time ng test
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/material/core : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @angular/material/button : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/material/snack-bar : es2015 as esm2015
⠋ Generating browser application bundles...23 01 2021 04:08:51.468:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
23 01 2021 04:08:51.470:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
23 01 2021 04:08:51.474:INFO [launcher]: Starting browser Firefox
✔ Browser application bundle generation complete.
23 01 2021 04:09:01.897:INFO [Firefox 84.0 (Fedora 0.0.0)]: Connected on socket R0BF6Acq7-LdXAJ0AAAA with id 61972481
Firefox 84.0 (Fedora 0.0.0) QuizService should be created FAILED
        NullInjectorError: R3InjectorError(DynamicTestModule)[QuizService -> HttpClient -> HttpClient]:
          NullInjectorError: No provider for HttpClient! in vendor.js (line 60828)
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'QuizService', 'HttpClient', 'HttpClient' ] })
        get@vendor.js:60828:27
        get@vendor.js:60995:33
        get@vendor.js:60995:33
        injectInjectorOnly@vendor.js:54558:33
        ɵɵinject@vendor.js:54562:61
        QuizService_Factory@ng:///QuizService/ɵfac.js:5:39
        hydrate@vendor.js:61163:35
        get@vendor.js:60984:33
        get@vendor.js:75064:33
        inject@vendor.js:87283:52
        inject@vendor.js:87208:37
        XPlr/</<@main.js:541:81
        invoke@polyfills.js:3294:30
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:41071:43
        invoke@polyfills.js:3293:36
        run@polyfills.js:3053:47
        runInTestZone@vendor.js:41324:38
        wrapTestInZone/<@vendor.js:41339:24
        <Jasmine>
        invokeTask@polyfills.js:3329:35
        runTask@polyfills.js:3097:51
        drainMicroTaskQueue@polyfills.js:3499:39
        Expected undefined to be truthy.
        <Jasmine>
        XPlr/</<@main.js:544:25
        invoke@polyfills.js:3294:30
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:41071:43
        invoke@polyfills.js:3293:36
        run@polyfills.js:3053:47
        runInTestZone@vendor.js:41324:38
        wrapTestInZone/<@vendor.js:41339:24
        <Jasmine>
        invokeTask@polyfills.js:3329:35
        runTask@polyfills.js:3097:51
        drainMicroTaskQueue@polyfills.js:3499:39
Firefox 84.0 (Fedora 0.0.0): Executed 1 of 6 (1 FAILED) (0 secs / 0.042 secs)
Firefox 84.0 (Fedora 0.0.0) QuizService should be created FAILED
        NullInjectorError: R3InjectorError(DynamicTestModule)[QuizService -> HttpClient -> HttpClient]:
          NullInjectorError: No provider for HttpClient! in vendor.js (line 60828)
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'QuizService', 'HttpClient', 'HttpClient' ] })
        get@vendor.js:60828:27
        get@vendor.js:60995:33
        get@vendor.js:60995:33
        injectInjectorOnly@vendor.js:54558:33
        ɵɵinject@vendor.js:54562:61
        QuizService_Factory@ng:///QuizService/ɵfac.js:5:39
        hydrate@vendor.js:61163:35
        get@vendor.js:60984:33
        get@vendor.js:75064:33
        inject@vendor.js:87283:52
        inject@vendor.js:87208:37
        XPlr/</<@main.js:541:81
        invoke@polyfills.js:3294:30
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:41071:43
        invoke@polyfills.js:3293:36
        run@polyfills.js:3053:47
        runInTestZone@vendor.js:41324:38
        wrapTestInZone/<@vendor.js:41339:24
        <Jasmine>
        invokeTask@polyfills.js:3329:35
        runTask@polyfills.js:3097:51
        drainMicroTaskQueue@polyfills.js:3499:39
        Expected undefined to be truthy.
        <Jasmine>
        XPlr/</<@main.js:544:25
        invoke@polyfills.js:3294:30
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:41071:43
        invoke@polyfills.js:3293:36
        run@polyfills.js:3053:47
        runInTestZone@vendor.js:41324:38
        wrapTestInZone/<@vendor.js:41339:24
        <Jasmine>
        invokeTask@polyfills.js:3329:35
        runTask@polyfills.js:3097:51
Firefox 84.0 (Fedora 0.0.0) QuizComponent should create FAILED
        NullInjectorError: R3InjectorError(DynamicTestModule)[QuizService -> HttpClient -> HttpClient]:
          NullInjectorError: No provider for HttpClient! in vendor.js (line 60828)
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'QuizService', 'HttpClient', 'HttpClient' ] })
        get@vendor.js:60828:27
        get@vendor.js:60995:33
        get@vendor.js:60995:33
        injectInjectorOnly@vendor.js:54558:33
        ɵɵinject@vendor.js:54562:61
        QuizService_Factory@ng:///QuizService/ɵfac.js:5:39
        hydrate@vendor.js:61163:35
        get@vendor.js:60984:33
        get@vendor.js:75064:33
        get@vendor.js:74778:35
        lookupTokenUsingModuleInjector@vendor.js:53151:39
        getOrCreateInjectable@vendor.js:53263:12
        ɵɵdirectiveInject@vendor.js:64433:12
        QuizComponent_Factory@ng:///QuizComponent/ɵfac.js:5:41
        getNodeInjectable@vendor.js:53358:44
        instantiateRootComponent@vendor.js:59867:40
        createRootComponent@vendor.js:62179:47
        create@vendor.js:74867:25
        initComponent@vendor.js:87337:51
        invoke@polyfills.js:3294:30
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:41071:43
        invoke@polyfills.js:3293:36
        onInvoke@vendor.js:78323:33
        invoke@polyfills.js:3293:36
        run@polyfills.js:3053:47
        run@vendor.js:78207:28
        createComponent@vendor.js:87340:41
        createComponent@vendor.js:87215:37
        QpGO/</<@main.js:328:81
        invoke@polyfills.js:3294:30
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:41071:43
        invoke@polyfills.js:3293:36
        run@polyfills.js:3053:47
        runInTestZone@vendor.js:41324:38
        wrapTestInZone/<@vendor.js:41339:24
        <Jasmine>
        invoke@polyfills.js:3294:30
        run@polyfills.js:3053:47
        scheduleResolveOrReject/<@polyfills.js:3787:40
        invokeTask@polyfills.js:3329:35
        runTask@polyfills.js:3097:51
        drainMicroTaskQueue@polyfills.js:3499:39
        Expected undefined to be truthy.
        <Jasmine>
        QpGO/</<@main.js:333:27
        invoke@polyfills.js:3294:30
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:41071:43
        invoke@polyfills.js:3293:36
        run@polyfills.js:3053:47
        runInTestZone@vendor.js:41324:38
        wrapTestInZone/<@vendor.js:41339:24
        <Jasmine>
        invoke@polyfills.js:3294:30
        run@polyfills.js:3053:47
        scheduleResolveOrReject/<@polyfills.js:3787:40
        invokeTask@polyfills.js:3329:35
        runTask@polyfills.js:3097:51
        drainMicroTaskQueue@polyfills.js:3499:39
Firefox 84.0 (Fedora 0.0.0): Executed 2 of 6 (2 FAILED) (0 secs / 0.12 secs)
Firefox 84.0 (Fedora 0.0.0) QuizComponent should create FAILED
        NullInjectorError: R3InjectorError(DynamicTestModule)[QuizService -> HttpClient -> HttpClient]:
          NullInjectorError: No provider for HttpClient! in vendor.js (line 60828)
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'QuizService', 'HttpClient', 'HttpClient' ] })
        get@vendor.js:60828:27
        get@vendor.js:60995:33
        get@vendor.js:60995:33
        injectInjectorOnly@vendor.js:54558:33
        ɵɵinject@vendor.js:54562:61
        QuizService_Factory@ng:///QuizService/ɵfac.js:5:39
        hydrate@vendor.js:61163:35
        get@vendor.js:60984:33
        get@vendor.js:75064:33
        get@vendor.js:74778:35
        lookupTokenUsingModuleInjector@vendor.js:53151:39
        getOrCreateInjectable@vendor.js:53263:12
        ɵɵdirectiveInject@vendor.js:64433:12
        QuizComponent_Factory@ng:///QuizComponent/ɵfac.js:5:41
        getNodeInjectable@vendor.js:53358:44
        instantiateRootComponent@vendor.js:59867:40
        createRootComponent@vendor.js:62179:47
        create@vendor.js:74867:25
        initComponent@vendor.js:87337:51
        invoke@polyfills.js:3294:30
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:41071:43
        invoke@polyfills.js:3293:36
        onInvoke@vendor.js:78323:33
        invoke@polyfills.js:3293:36
        run@polyfills.js:3053:47
        run@vendor.js:78207:28
        createComponent@vendor.js:87340:41
        createComponent@vendor.js:87215:37
        QpGO/</<@main.js:328:81
        invoke@polyfills.js:3294:30
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:41071:43
        invoke@polyfills.js:3293:36
        run@polyfills.js:3053:47
        runInTestZone@vendor.js:41324:38
        wrapTestInZone/<@vendor.js:41339:24
        <Jasmine>
        invoke@polyfills.js:3294:30
        run@polyfills.js:3053:47
        scheduleResolveOrReject/<@polyfills.js:3787:40
        invokeTask@polyfills.js:3329:35
        runTask@polyfills.js:3097:51
        drainMicroTaskQueue@polyfills.js:3499:39
        Expected undefined to be truthy.
        <Jasmine>
        QpGO/</<@main.js:333:27
        invoke@polyfills.js:3294:30
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:41071:43
        invoke@polyfills.js:3293:36
        run@polyfills.js:3053:47
        runInTestZone@vendor.js:41324:38
        wrapTestInZone/<@vendor.js:41339:24
        <Jasmine>
        invoke@polyfills.js:3294:30
        run@polyfills.js:3053:47
        scheduleResolveOrReject/<@polyfills.js:3787:40
        invokeTask@polyfills.js:3329:35
        runTask@polyfills.js:3097:51
ERROR: 'NG0304: 'app-loading' is not a known element:
1. If 'app-loading' is an Angular component, then verify that it is part of this module.
2. If 'app-loading' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
Firefox 84.0 (Fedora 0.0.0): Executed 4 of 6 (2 FAILED) (0 secs / 0.156 secs)
ERROR: 'NG0304: 'app-loading' is not a known element:
1. If 'app-loading' is an Angular component, then verify that it is part of this module.
Firefox 84.0 (Fedora 0.0.0): Executed 6 of 6 (2 FAILED) (0.252 secs / 0.206 secs)
TOTAL: 2 FAILED, 4 SUCCESS
TOTAL: 2 FAILED, 4 SUCCESS

real    0m41.508s
user    1m29.766s
sys     0m4.165s