add timer to quiz
say something like
Congratulations, you've completed the test in under 33 seconds.

[kushal@fedora coloradoquiz]$ date; cd ~/src/angular/coloradoquiz; time sh update.sh; time git push origin master; date;
Sat Jun 25 07:13:37 PM EDT 2022
[master e86417ae5] add timestamp
 1 file changed, 1 insertion(+), 44 deletions(-)
 rewrite README.md (100%)
[master 839dc2807] begin add system status
 1 file changed, 11 insertions(+)
[master b9cea336f] add system status
 1 file changed, 6 insertions(+)
[master 90e17c50a] end add system status
 1 file changed, 1 insertion(+)
[master b1a6ac7ff] begin update node
 1 file changed, 1 insertion(+)
Installing latest LTS version.
v16.15.1 is already installed.
Now using node v16.15.1 (npm v8.11.0)

real    0m1.104s
user    0m0.727s
sys     0m0.308s
Now using node v16.15.1 (npm v8.11.0)

real    0m0.530s
user    0m0.371s
sys     0m0.244s
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 220 packages, and audited 221 packages in 13s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

real    0m12.906s
user    0m9.443s
sys     0m2.865s
Error: You need to specify a command before moving on. Use '--help' to view the available commands.
error Command failed with exit code 1.

real    0m0.904s
user    0m0.847s
sys     0m0.143s

real    0m0.800s
user    0m1.058s
sys     0m0.068s
[master 214c4a161] end update node
 1 file changed, 8 insertions(+)
On branch master
Your branch is ahead of 'origin/master' by 7 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
yarn run v1.22.19
$ ng update @angular/core @angular/cli @angular/material @angular/localize
Using package manager: yarn
Collecting installed dependencies...
Found 35 dependencies.
Fetching dependency metadata from registry...
Package '@angular/core' is already up to date.
Package '@angular/cli' is already up to date.
Package '@angular/material' is already up to date.
Package '@angular/localize' is already up to date.
Done in 2.35s.

real    0m2.562s
user    0m1.586s
sys     0m0.308s
On branch master
Your branch is ahead of 'origin/master' by 7 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
[master 97430134f] begin prepare to build angular
 1 file changed, 1 insertion(+)
- Generating browser application bundles (phase: setup)...
WARNING: The same color styles are generated multiple times. Read more about how style duplication can be avoided in a dedicated guide. https://github.com/angular/components/blob/main/guides/duplicate-theming-styles.md
    node_modules/@angular/material/core/theming/_theming.scss 325:7   private-check-duplicate-theme-styles()
    node_modules/@angular/material/core/theming/_all-theme.scss 42:3  all-component-themes()
    src/styles.scss 58:1                                              root stylesheet

✔ Browser application bundle generation complete.
✔ Browser application bundle generation complete.
- Copying assets...
✔ Copying assets complete.
- Generating index html...
✔ Index html generation complete.
- Generating service worker...
✔ Service worker generation complete.

real    1m49.410s
user    2m55.226s
sys     0m7.608s
[master 7823da76c] end prepare to build angular
 1 file changed, 14 insertions(+)
[master 0525a58ff] begin prepare to unit test angular
 1 file changed, 1 insertion(+), 8436 deletions(-)
 rewrite locallog/fedoratest.md (99%)
- Generating browser application bundles (phase: setup)...
WARNING: The same color styles are generated multiple times. Read more about how style duplication can be avoided in a dedicated guide. https://github.com/angular/components/blob/main/guides/duplicate-theming-styles.md
    node_modules/@angular/material/core/theming/_theming.scss 325:7   private-check-duplicate-theme-styles()
    node_modules/@angular/material/core/theming/_all-theme.scss 42:3  all-component-themes()
    src/styles.scss 58:1                                              root stylesheet

✔ Browser application bundle generation complete.
✔ Browser application bundle generation complete.
✔ Browser application bundle generation complete.
error Command failed with exit code 1.

real    3m41.457s
user    5m43.921s
sys     0m25.512s
[master 90edaf380] end prepare to unit test angular
 1 file changed, 8504 insertions(+)
[master c6b7d3f5e] add timestamp
 1 file changed, 1 insertion(+)

real    5m53.442s
user    8m54.440s
sys     0m39.856s
Enumerating objects: 61, done.
Counting objects: 100% (61/61), done.
Delta compression using up to 8 threads
Compressing objects: 100% (46/46), done.
Writing objects: 100% (48/48), 89.38 KiB | 1.21 MiB/s, done.
Total 48 (delta 30), reused 2 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (30/30), completed with 12 local objects.
To github.com:teamkushal/coloradoquiz.git
   f17edcde0..c6b7d3f5e  master -> master

real    0m1.933s
user    0m0.173s
sys     0m0.046s
Sat Jun 25 07:19:32 PM EDT 2022
[kushal@fedora coloradoquiz]$ date; time yarn start; date;
Sat Jun 25 07:31:19 PM EDT 2022
yarn run v1.22.19
$ export NODE_OPTIONS="--max-old-space-size=6144"; ng serve --host=0.0.0.0 --disable-host-check --hmr=true
NOTICE: Hot Module Replacement (HMR) is enabled for the dev server.
See https://webpack.js.org/guides/hot-module-replacement for information on working with HMR for Webpack.
Warning: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
main.js               | main          |   7.79 MB |
vendor.js             | vendor        |   5.76 MB |
polyfills.js          | polyfills     |   1.16 MB |
styles.css, styles.js | styles        | 465.76 kB |
runtime.js            | runtime       |  48.11 kB |

                      | Initial Total |  15.21 MB

Build at: 2022-06-25T23:33:26.592Z - Hash: 07f1d73a738d64fd - Time: 122988ms

** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.07f1d73a738d64fd.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.07f1d73a738d64fd.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-25T23:40:29.597Z - Hash: 21c9ae8c3b118a14 - Time: 45939ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.21c9ae8c3b118a14.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.21c9ae8c3b118a14.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-25T23:45:18.028Z - Hash: de1d4b5ac1d630cb - Time: 42123ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.de1d4b5ac1d630cb.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.de1d4b5ac1d630cb.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-25T23:45:55.687Z - Hash: ba27073f7c322113 - Time: 36877ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2022-06-25T23:50:58.874Z - Hash: ba27073f7c322113 - Time: 42081ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.ba27073f7c322113.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.ba27073f7c322113.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-25T23:51:37.837Z - Hash: b5a4150ba842c285 - Time: 38424ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.b5a4150ba842c285.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.b5a4150ba842c285.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-25T23:52:21.388Z - Hash: fa2698f5c597eea6 - Time: 43155ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2022-06-25T23:53:02.196Z - Hash: fa2698f5c597eea6 - Time: 40337ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2022-06-25T23:53:49.788Z - Hash: fa2698f5c597eea6 - Time: 39924ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.fa2698f5c597eea6.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.fa2698f5c597eea6.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-25T23:57:18.432Z - Hash: 9451e3c620786b84 - Time: 41857ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.9451e3c620786b84.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.9451e3c620786b84.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-25T23:57:58.027Z - Hash: 8b736068b519fa3c - Time: 38727ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.8b736068b519fa3c.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.8b736068b519fa3c.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-25T23:58:35.200Z - Hash: e9f0060ad402d2c9 - Time: 36788ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.e9f0060ad402d2c9.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.e9f0060ad402d2c9.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-25T23:59:14.133Z - Hash: 273964f83be606e5 - Time: 38486ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.273964f83be606e5.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.273964f83be606e5.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-26T00:00:49.244Z - Hash: 7af6f2043369ffc4 - Time: 44085ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.7af6f2043369ffc4.hot-update.js       | main    |  7.83 MB |
runtime.js, runtime.7af6f2043369ffc4.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-26T00:03:45.740Z - Hash: e9e92e0e2ee441a7 - Time: 42796ms

./src/app/quiz/quiz.component.ts:109:16 - Error: Module parse failed: Unexpected token (109:16)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|             if (time === 1) {
|                 message = `Congratulations, you've completed the test in under ${time} second.`,
>                 ;
|             }
|             else if (time > 1) {

Error: src/app/quiz/quiz.component.ts:112:7 - error TS1109: Expression expected.

112       } else if (time > 1) {
          ~

Error: src/app/quiz/quiz.component.ts:114:7 - error TS1109: Expression expected.

114       }
          ~

✖ Failed to compile.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.7af6f2043369ffc4.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.7af6f2043369ffc4.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-26T00:04:28.040Z - Hash: 26a0fb1ff675c397 - Time: 41407ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.26a0fb1ff675c397.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.26a0fb1ff675c397.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-26T00:05:39.304Z - Hash: 6ebae4c10b8177bb - Time: 43788ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.6ebae4c10b8177bb.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.6ebae4c10b8177bb.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-26T00:07:01.735Z - Hash: 19b7526692885db5 - Time: 45161ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files                                | Names   | Raw Size
main.js, main.19b7526692885db5.hot-update.js       | main    |  7.81 MB |
runtime.js, runtime.19b7526692885db5.hot-update.js | runtime | 48.45 kB |

3 unchanged chunks

Build at: 2022-06-26T00:07:41.288Z - Hash: 6cc02786a0bafc3d - Time: 38698ms

✔ Compiled successfully.
^C
real    37m20.073s
user    0m0.940s
sys     0m0.160s

[kushal@fedora coloradoquiz]$